team-Melissa/melissa-FE

package.json
pnpm-lock.yaml
src/apis/loginApi.ts
src/hooks/useLogin.ts
src/pages/Login/index.tsx

- [react-native-google-signin](https://react-native-google-signin.github.io) 라이브러리를 활용해 구글 `id token`을 발급받고, 백엔드로 로그인 요청을 날리도록 설계. 
- 구글 로그인 요청을 수행하는 `googleLoginFn` 구현
- 전체 요청을 수행하는 로직은 Tanstack-query의 `useMutation` 활용.
- 3사 로그인을 처리하는 커스텀 훅 `useLogin`에 `googleMutate` 추가
- `access token`을 저장할 때 `tokenType`을 붙여 저장하도록 변경
---
---
> 테스트 환경: 구글 미설치 & IOS / 구글 설치 & AOS
>
> 구글 설치 & IOS, 구글 미설치 & AOS는 추후 테스트가 필요합니다.
---
1. `Google Developer Console` 설정을 마치고 AOS에서 로그인 하자, 나머지 값들은 잘 받아오지만 정작 필요한 `id token`을 받아오지 못하는 문제 발생
- [Github Issue](https://github.com/react-native-google-signin/google-signin/issues/836)를 읽어보다 보니 `id token`을 받으려면 `Web client`도 등록하고, `GoogleSignin.configure`에 `webClientId` 필드를 추가해줘야 한다는 내용이 있어 시도
- `webClientId`를 추가하자 `id token`이 잘 받아와짐
2. AOS에서 앱과 `Google Developer Console`에 …

구글 OAuth 로그인 구현

---

src/apis/threadApi.ts
src/constants/endpoint.ts
src/constants/toastMessage.ts
src/hooks/useUpdateDiary.ts
src/libs/showToast.ts
src/pages/Calendar/DayComponent/index.tsx
src/pages/Chatting/index.tsx

일기 요약 API를 채팅 페이지 언마운트에 트리거하기

---

app.config.ts
eas.json

만약 해당 PR을 머지했을 때 빌드 및 업로드가 잘 수행된다면, 추후 main 브랜치로 PR을 머지하면 정상적으로 빌드와 업로드가 수행된다.

EAS build, submit을 활용해 앱스토어/플레이스토어에 자동으로 업로드되도록 CICD 구성 및 테스트 진행

---

src/pages/Setting/index.tsx

설정 페이지에 존재하는 buy me a coffee 링크로 인해 애플 앱 심사 리젝 발생.
인 앱 결제 방식으로만 통과 가능해보인다.
---
---

후원하기 기능 제거

---

app.config.ts
metro.config.js
package.json
pnpm-lock.yaml
src/app/_layout.tsx
src/pages/Login/index.tsx

close #31 
런타임 에러 디버깅을 위해 Sentry 도입
sentry 사이트에서 직접 모니터링 가능합니다. id/pw는 confluence를 확인해주세요!
> 추가된 환경변수가 있으므로, 빌드가 안 된다면 confluence를 확인해주세요!
```
SENTRY_ORG
SENTRY_PROJECT
SENTRY_AUTH_TOKEN
EXPO_PUBLIC_SENTRY_DSN
```
| 기능 | 스크린샷 |
| :--: | :------: |
| 세션 리플레이     |     <img width="922" alt="스크린샷 2025-03-16 01 01 36" src="https://github.com/user-attachments/assets/c8222617-82f2-4313-b5cc-6d9fcd864f1d" /> |
| 스택 트레이스     |  <img width="904" alt="스크린샷 2025-03-16 01 01 41" src="https://github.com/user-attachments/assets/808d7fc9-ab85-44ea-997f-0c87117e314d" />   |
| 실행 환경     |   <img width="926" alt="스크린샷 2025-03-16 01 01 48" src="https://github.com/user-attachments/assets/d7d47011-da67-4866-b652-c3a43870e18d" /> |

실 배포 환경 런타임 에러 디버깅을 위해 Sentry 도입

---

src/app/_layout.tsx

close #38 
Sentry가 개발 환경에서 실행되지 않도록 막아줌 ([참고 Github](https://gist.github.com/MirzaLeka/d709d0925d9b749d1b9068abf4b5ad50?permalink_comment_id=5164006#gistcomment-5164006))

Sentry가 개발 환경에서도 에러를 리포팅하는 문제 해결

---

pnpm-lock.yaml
src/components/AssistantList/AssistantCard/index.tsx
src/components/AssistantList/styles.ts
src/components/ProgressBar/styles.ts
src/pages/MakeAssistant/Question/index.tsx
src/pages/MakeAssistant/Question/styles.ts

issues 에 있는 것들 여기에 연결 못시키나
> ### 📌 Feature Issue
> 민서 QA 실 적용. Due 25/03/16 일요일.
> 
> ### 📝 To-do
> * [x]  진행바 색상 저번에 말씀드린걸로 변경[x]  진행바 위에 질문 숫자 조금 더 아래로 내려와도 될 것 같아요 5px만 더 아래로[x]  프로필 사진에 그림자 있어야할 것 같아요 말풍선이랑 똑같은 그림자[x]  카드 삭제할 때 진짜 삭제할건지 팝업창 하나 뜨면 좋을 것 같아요
이거 했습니다!

UI fixes by ms

---

app.config.ts

[main] Melissa 1.0.2

---

app.config.ts

[dev] 앱 버전 1.0.2로 업데이트 (IOS submit 실패 대응)

---

package.json
pnpm-lock.yaml
src/libs/axiosInstance.test.ts
src/libs/axiosInstance.ts

close #62 
백엔드 측에서 깜빡하고 token expired 값 조절을 놓쳐 발생한 이슈였다.
(테스트 코드 공부했으니 굿 ㅎㅎ)

[dev] axios interceptor 토큰 재발급 로직 테스트 코드 추가

---

app.config.ts
src/libs/axiosInstance.test.ts

[dev] 앱 버전 업데이트

---

.github/workflows/eas-update.yaml

[dev] Github Actions로 Eas Build, Submit, Update를 모두 처리하도록 변경

---

.github/workflows/eas-update.yaml

[dev] Github Actions 워크플로 수정

---

.github/workflows/eas-update.yaml

[dev] Github Actions의 EAS build에 platform flag 추가

---

.github/workflows/eas-update.yaml

[dev] Github Actions에 필요한 환경변수 추가

---

.github/workflows/eas-update.yaml

[dev] EAS Update 시 production 환경변수를 사용하도록 Github Actions 스크립트 변경

---

src/features/assistantList/hooks/mutations/useRemoveAssistantMutation.ts

close #101 
<table>
<tr>
<th>Glare Before</th>
<th>After</th>
</tr>
<tr>
<td><img width="224" src="https://github.com/user-attachments/assets/977c520f-0145-46e7-987b-51b902d170a5" /></td>
<td><img width="224" src="https://github.com/user-attachments/assets/eabacf12-b4b8-445f-bfbf-42b1129a899e" /></td>
</tr>
</table>

[dev] AI 프로필 삭제가 불가능한 문제 개선

---

src/features/assistantList/hooks/mutations/useRemoveAssistantMutation.ts
src/features/setting/components/SleepTimeSettingItem.tsx

#102 핫픽스를 상용 배포합니다. (EAS Update)

[main] AI 프로필 삭제가 불가능한 문제 개선

---

.github/workflows/check-labels.yaml

[main] Github Actions workflow 문법 오류 대응

---

.github/workflows/check-labels.yaml

#126 #128 작업 이후 환경변수(EXPO_TOKEN, GOOGLE_IOS_URL_SCHEME)가 제대로 전달되지 않는 문제를 대응합니다.

[dev] called된 workflow에서 환경변수가 누락되는 문제 수정

---

src/features/setting/containers/SettingContainer.tsx
src/utils/initializeApp.ts

#134 작업 상용 배포 PR입니다. (EAS update)

[main] 앱 실행 시 EAS update 즉시 적용 로직 구현

---

src/features/setting/containers/SettingContainer.tsx

[main] 실제 OTA 버전이 있을 때만 설정에서 확인할 수 있도록 변경

---

src/app/_layout.tsx
src/modules/modal/components/ModalRoot.tsx
src/modules/modal/components/Modals.tsx
src/modules/modal/context/ModalDispatchContext.tsx
src/modules/modal/hooks/useModal.ts
src/modules/modal/index.ts
src/modules/modal/provider/ModalsProvider.tsx
src/modules/modal/types/index.ts

[main] 일기 수동 작성 기능 구현을 위한 선언형 모달 세팅
